export interface GenericDataResponse<T> {
    data: T[];
}

export interface UniverseData {
    id: number;
    rootPlaceId: number;
    name: string;
    description: string;
    sourceName?: string;
    sourceDescription?: string;
    creator: any; // TODO?
    price?: number;
    allowedGearGenres: string[];
    allowedGearCategories: string[];
    isGenreEnforced: boolean;
    copyingAllowed: boolean;
    playing: number;
    visits: number;
    maxPlayers: number;
    created: string;
    updated: string;
    studioAccessToApisAllowed: boolean;
    createVipServersAllowed: boolean;
    universeAvatarType: string;
    genre: string;
    genre_l1: string;
    genre_l2: string;
    untranslated_genre_l1: string;
    isAllGenre: boolean;
    isFavoritedByUser: boolean;
    favoritedCount: number;
}

export interface UniverseResponse {
    universeId: number;
}

export interface ThumbnailData {
    requestId: string;
    targetId: number;
    type: AssetType;
    size: string;
    format: ThumbnailFormat;
    isCircular: boolean;
}

export interface ThumbnailResponse {
    requestId: string;
    errorCode: number;
    errorMessage: string;
    targetId: number;
    state: string;
    imageUrl?: string;
    version?: string;
}

export type AssetType =
    | "Avatar"
    | "AvatarHeadShot"
    | "GameIcon"
    | "BadgeIcon"
    | "GameThumbnail"
    | "GamePass"
    | "Asset"
    | "BundleThumbnail"
    | "Outfit"
    | "GroupIcon"
    | "DeveloperProduct"
    | "AutoGeneratedAsset"
    | "AvatarBust"
    | "PlaceIcon"
    | "AutoGeneratedGameIcon"
    | "ForceAutoGeneratedGameIcon"
    | "Look"
    | "CreatorContextAsset"
    | "Screenshot";

export type ThumbnailFormat = "png" | "jpeg" | "webp" | "gif" | "bmp";
